### ISSUE TITLE
Question: RoleBinding fixed namespace to kube-system

### ISSUE THREAD

**Issue by awuetz** [kubeops-tools/kubed#475]
Hello kubed Team,

is there a special need why the RoleBinding is fixed to the namespace `kube-system` ?

```yaml
kind: RoleBinding
  metadata:
    name: {{ template "kubed.fullname" . }}-apiserver-extension-server-authentication-reader
    namespace: kube-system
```
I fell over this, because we have a managed kubernetes service where I wanted to use kubed, but the installation failed, because we have no permissions for this `kube-system` namespace.

Would it make sense to have it implemented like the other resources?

Kubed version: v0.12.0
